name: clang-format Check

on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: lucasssvaz/arduino-esp32-format@v1.0
      with:
        clang-format-version: '15'
        check-path: ${{ matrix.path }}
        changed-only: 'true'
