name: Report Pre-commit Check Status

on:
  workflow_run:
    workflows: [Pre-commit hooks]
    types:
      - completed

permissions:
  statuses: write

jobs:
  get-pr-number:
    name: Get PR number
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.pr_num_reader.outputs.content }}
    steps:
    - name: Download and Extract Artifacts
      run: |
        artifacts_url=${{ github.event.workflow_run.artifacts_url }}
        gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
        do
          IFS=$'\t' read name url <<< "$artifact"
          gh api $url > "$name.zip"
          unzip -j "$name.zip" -d "temp_$name"
          if [[ "$name" == "pr_num" ]]; then
            mv "temp_$name"/* .
          fi
          rm -r "temp_$name"
        done
        echo "Contents of directory:"
        ls -la

    - name: Read the pr_num file
      id: pr_num_reader
      uses: juliangruber/read-file-action@v1
      with:
        path: ./pr_num.txt

  report-success:
    name: Report pre-commit success
    needs: get-pr-number
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Report success
        uses: actions/github-script@v6
        with:
          script: |
            const {owner, repo} = '${{ github.repository }}'.split('/');
            const sha = (await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: '${{ needs.get-pr-number.outputs.pr }}',
            })).data.head.sha;
            core.debug(`owner: ${owner}`);
            core.debug(`repo: ${repo}`);
            core.debug(`sha: ${sha}`);
            const { context: name, state } = (await github.rest.repos.createCommitStatus({
              context: 'Pre-commit checks',
              description: 'Pre-commit checks successful',
              owner: owner,
              repo: repo,
              sha: sha,
              state: 'success',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}'
            })).data;
            core.info(`${name} is ${state}`);

  report-pending:
    name: Report pre-commit pending
    needs: get-pr-number
    if: github.event.workflow_run.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Report pending
        uses: actions/github-script@v6
        with:
          script: |
            const {owner, repo} = '${{ github.repository }}'.split('/');
            const sha = (await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: '${{ needs.get-pr-number.outputs.pr }}',
            })).data.head.sha;
            core.debug(`owner: ${owner}`);
            core.debug(`repo: ${repo}`);
            core.debug(`sha: ${sha}`);
            const { context: name, state } = (await github.rest.repos.createCommitStatus({
              context: 'Pre-commit checks',
              description: 'The pre-commit checks need to be successful before merging',
              owner: owner,
              repo: repo,
              sha: sha,
              state: 'pending',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}'
            })).data;
            core.info(`${name} is ${state}`);
