name: Run Pre-commit Checks

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  statuses: write

jobs:
  report-pending:
    name: Report pre-commit workflow as pending
    runs-on: ubuntu-latest
    steps:
      - name: Report pending
        uses: conda/actions/set-commit-status@v24.2.0
        with:
          context: "Pre-commit checks"
          state: pending
          description: The pre-commit checks need to be successful before merging

  run-pre-commit:
    name: Run pre-commit checks
    needs: report-pending
    if: |
      contains(github.event.pull_request.labels.*.name, 'Status: Pending Merge')
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit

  report-success:
    name: Push changes and report success
    needs: run-pre-commit
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'Status: Pending Merge') &&
      needs.run-pre-commit.result == 'success'
    steps:
      - name: Push changes using pre-commit-ci-lite
        uses: lucasssvaz/lite-action@main
        with:
          msg: "ci(pre-commit): Apply automatic fixes"
          run: ${{ needs.run-pre-commit.outputs.run-id }}

      - name: Report success
        uses: conda/actions/set-commit-status@v24.2.0
        with:
          context: "Pre-commit checks"
          state: success
          description: All pre-commit checks passed
