name: Pre-commit check

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  lint:
#    if: |
#      contains(github.event.pull_request.labels.*.name, 'Status: Pending Merge')
    name: Checking if any fixes are needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - id: changed-files
        uses: tj-actions/changed-files@v42.0.2
      - if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'Full Pre-commit Check') }}
        name: Full pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      - if: ${{ github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'Full Pre-commit Check') }}
        name: Local pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
