name: Publish test results

on:
  workflow_run:
    workflows: ["Wokwi tests"]
    types:
      - completed

# No permissions by default
permissions: { contents: read }

jobs:
  unit-test-results:
    name: Unit Test Results
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == 'failure' ||
      github.event.workflow_run.conclusion == 'timed_out'
    runs-on: ubuntu-latest
    permissions:
        actions: read
        checks: write
        pull-requests: write
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: ./artifacts

      - name: Get original info
        run: |
          original_event=$(cat ./artifacts/event.txt)
          original_sha=$(cat ./artifacts/sha.txt)
          echo "original_event=$original_event" >> $GITHUB_ENV
          echo "original_sha=$original_sha" >> $GITHUB_ENV

          echo "original_event = $original_event"
          echo "original_sha = $original_sha"

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ env.original_sha }}
          event_file: ./artifacts/event_file/event.json
          event_name: ${{ env.original_event }}
          files: ./artifacts/**/*.xml
